name: "Echo Action"
description: "An action that echoes a message"

inputs:
  message:
    description: "The message to echo"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.message }}
