name: "Echo Action"
description: "An action that echoes a message (this is the action metadata file)"

inputs:
  message:
    description: "The message to echo"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.message }}
