name: Test Log and Comment Action

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, assigned,unassigned, closed, reopened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Match the version you're using

      - name: Install dependencies
        run: npm ci
        working-directory: ./.github/actions/my-js-action

      - name: Run custom action
        uses: ./.github/actions/my-js-action
        with:
          message: 'Hello, this is a test comment from the custom action!'
          github-token: ${{ secrets.GITHUB_TOKEN }}
